export { default as Home } from './home/Home';
export { default as NavBar } from './navbars/main/Navbar';
export { default as Products } from './products/Products';
// export { default as Cart } from './cart/Cart';
// export { default as Checkout } from './checkoutForm/checkout/Checkout';
// export { default as ProductDetails } from './products/productDetail/ProductDetails';
export { default as PdoductsByCategory } from './products/productsbycategory/PdoductsByCategory';
export { default as Footer } from './footer/Footer';
export { default as About } from './about/About';
export { default as Policy } from './policy/Policy';
